### ISSUE TITLE
[Video mode] Videos don't start from the beginning

### ISSUE THREAD

**Issue by RickyM7** [libre-tube/LibreTube#2566]
### Steps to reproduce

1. Start a queue playback
2. Put a shorter duration sound to play before a longer duration one

After the shortest sound ends, the longest sound will start from the minute the previous one ended.

### Expected behavior

Every song starts from 0 (minute 00:00) on the queue.

### Actual behavior

Some songs don't starts from 0

### LibreTube version

0.9.1

### Android version

Android 11 (ArrowOS)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The issue is about using the "background mode" (without visible video player)?

**Comment by RickyM7** [comment]
> The issue is about using the "background mode" (without visible video player)?

Yes!

**Comment by Xephobia** [comment]
Can confirm on my device

**Comment by RickyM7** [comment]
@Bnyro This is still happening, but only sometimes, and only when I'm watching videos (I don't recall seeing this happen again in audio mode).

 Note: I tagged you because I don't know if you would see this if I just commented, but if I didn't need to tag you, let me know and I won't tag you next time.

LT Version: 0.11.0

**Comment by Bnyro** [comment]
I read all the messages anyways, I prefer to not get tagged as already mentioned in our Code of Conduct.

**Comment by Bnyro** [comment]
Should be solved with #2999

**Comment by RickyM7** [comment]
> Should be solved with #2999

The bug remains in v0.12.0. It's like the next video gets the previous video's viewing history, which is weird.
