### ISSUE TITLE
Play in the background!

### ISSUE THREAD

**Issue by Legoks** [libre-tube/LibreTube#313]
As soon as you exit the application after the last update, the video stops and cannot be played in the background!

**Comment by Bnyro** [comment]
fixed already

**Comment by Legoks** [comment]
I'm running the latest version, but I still have the same problem.

**Comment by Bnyro** [comment]
it's fixed in the CI builds, it will be fixed in the next update

**Comment by Legoks** [comment]
Please look at the other problems I raised!
