### ISSUE TITLE
Tags and channel mentions in video description open in YouTube app

### ISSUE THREAD

**Issue by Kiisu-Master** [libre-tube/LibreTube#4980]
### Steps to reproduce

Tap on a tag or channel mention in a videos description

### Expected behavior

Shows tag or channel page in LibreTube

### Actual behavior

Opens tag or channel page in YouTube app

### LibreTube version

0.19.0 ( IzzyOnDroid )

### Android version

Android 11

### Other details

Tags only open in YouTube app when they are in the description text, not at the bottom.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Did you set LibreTube to be the default app for YouTube links? ![Screenshot_20231014_134936_Settings.jpg](https://github.com/libre-tube/LibreTube/assets/50032603/b7056492-de71-4409-aa0b-02cb754a69fd)

**Comment by Kiisu-Master** [comment]
I now tried to change the settings.
I cant toggle it per address like you can, but i can change it per app.
I disabled opening in YouTube app and enabled it in LibreTube.
Now tapping on tags gives me a option to open in vivaldi browser or mi video (i have a redmi), and channel mentions open in default browser (vivaldi).

**Comment by Kiisu-Master** [comment]
I also tried tapping on a channel mention in a comment.
It opened in LibreTube.
If i change my settings back it opens in YouTube.

**Comment by cool-dev-guy** [comment]
So is the issue fixed now?

**Comment by Kiisu-Master** [comment]
No, it's not fixed for me.
With these settings:
![image](https://github.com/libre-tube/LibreTube/assets/142301391/46453d3b-5b00-4f61-8f5a-ec859eff9247)
![image](https://github.com/libre-tube/LibreTube/assets/142301391/d0bc3228-8bd5-4102-a1e7-4979d413b270)

clicking on tags gives this option: ![image](https://github.com/libre-tube/LibreTube/assets/142301391/da8998c3-06f2-447b-b7d6-7c324f323cfc)

and clicking on channel mentions in a video description opens in Vivaldi (set as default browser).
When I click on a mention in a comment, it opens in LibreTube as expected.

**Comment by Kiisu-Master** [comment]
I removed Vivaldi as the default browser setting.
Now it gives options to open in all the browsers i have installed (Chrome, Firefox, Vivaldi, Mi Browser..).
The only place where its different is in the **comment section**.
When i click on a mention there it gives all the browsers **and** LibreTube as options.

**Comment by Bnyro** [comment]
Works fine for me, please feel free to reach out for further help via our Matrix room.
