### ISSUE TITLE
DeArrow doesnt work in subscriptions feed

### ISSUE THREAD

**Issue by FamiliarBreakfast** [libre-tube/LibreTube#5961]
### Steps to reproduce

Enable DeArrow
Check the subscriptions tab

### Expected behavior

Titles and thumbnails should be modified

### Actual behavior

Titles and thumbnails remain the same

### LibreTube version

0.23.0

### Android version

android 13

### Other details

DeArrow seems to work *most* of the time on channel pages and in recommendations, but not in home/sub feeds, watch history, downloads, and occasionally just at all for some videos at random.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by strangersdangers** [comment]
If I remember correctly, you have to wait for a few minutes so the changes apply.

**Comment by FamiliarBreakfast** [comment]
Even after several days and several refreshes nothing changes.

**Comment by Bnyro** [comment]
Fixed with https://github.com/libre-tube/LibreTube/pull/5983 and https://github.com/libre-tube/LibreTube/pull/5984 by introducing pagination the subscriptions feed for DeArrow, because previously we loaded DeArrow for all videos in the feed at once which certainly exceeded the request / server limit.

**Comment by rociomarielgnas** [comment]
Hello, sorry for commenting on a closed issue, but this is still happening to me on subscriptions tab.
![Screenshot_20240903-002838](https://github.com/user-attachments/assets/155f2686-2675-4d8f-bf27-f30989622029)
![Screenshot_20240903-002910](https://github.com/user-attachments/assets/59851cec-f59d-4719-90ec-7e3d3a4cf4c2)
