### ISSUE TITLE
Notification Player Buttons does not work on Samsung (maybe other phones also)

### ISSUE THREAD

**Issue by nachat-ayoub** [libre-tube/LibreTube#6878]
### Steps to reproduce

1- play a video in the audio only mode
2- navigate outside the app
3- click the notification player buttons (nothing works)

### Expected behavior

notification player buttons need to work

### Actual behavior

nothing happens when clicking the notification player buttons

### LibreTube version

0.25.2

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's already been fixed in the latest debug builds and will work again after the next update.

That only happens on some Android versions and ROMs btw, and re-installing the app also fixed it for some people.

**Comment by nachat-ayoub** [comment]
> That's already been fixed in the latest debug builds and will work again after the next update due to using a different library for building notifications.
> 
> That only happens on some Android versions and ROMs btw, and re-installing the app also fixed it for some people.

i uninstalled the app and installed the latest version but the issue still exists.
